# Generated by Django 6.0.3 on 2026-03-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default='correo@empresa.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='nit',
            field=models.CharField(default='000000000', max_length=20),
            preserve_default=False,
        ),
    ]
